swagger: '2.0'
info:
  title: Bank Argent API documentation for transactions
  description: Contains all available API endpoints for transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Retrieve all transactions
      description: Returns all transactions for the current month, grouped by user account
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '404':
          description: No transactions found for the current month
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Retrieve details of a specific transaction
      description: Returns the details (type,categroy and note) of a specific transaction identified by its ID
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
          description: ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransactionDetail'
        '404':
          description: Transaction not found for the specified ID

    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction
      description: Updates (category and note ) transaction identified by its ID
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
          description: ID of the transaction to update
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid transaction data
        '404':
          description: Transaction not found for the specified ID
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction
      description: Deletes a transaction identified by its ID
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
          description: ID of the transaction to delete
      responses:
        '204':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found for the specified ID
        '500':
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      transactionId:
        type: integer
      accountId:
        type: integer
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
      date:
        type: string

  TransactionDetail:
    type: object
    properties:
      type:
        type: string
      category:
        type: string
      note:
        type: string
      transactionId:
        type: integer
      accountId:
        type: integer
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
      date:
        type: string
  


